version: '2'
services:
  neo4j-gc2017:
    build: ./neo4j
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
  structr-gc2017:
    build: ./structr
    depends_on:
      - neo4j-gc2017
    links: 
      - neo4j-gc2017
    ports:
     - "8082:8082"