version: '3'
services:

  neo4j:
    image: neo4j:3.5
    networks:
      - structr-remote
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/structr
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - neo4j:/var/lib/neo4j

  structr:
    build: ./structr
    depends_on:
      - neo4j
    networks: 
      - structr-remote
    ports:
      - "8082:8082"
    volumes:
      - structr:/var/lib/structr


volumes:
  neo4j:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/mount/neo4j
  structr:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/mount/structr

networks:
  structr-remote: